import { Bookmark, BookmarkCheck, BriefcaseBusiness, Building2, CalendarDays, ExternalLink, MapPin, Search, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import AsyncState from "../components/common/AsyncState";
import { apiErrorMessage, careerApi } from "../services/careerApi";

const clean = (value = "") => value.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
const age = (value) => value ? new Intl.RelativeTimeFormat("en", { numeric: "auto" }).format(-Math.max(0, Math.floor((Date.now() - new Date(value)) / 86400000)), "day") : "Date unavailable";

function JobCard({ job, saved, onOpen, onSave }) {
  return <article className="job-card"><div className="job-card-top"><div className="job-company-mark">{job.company?.slice(0, 1)}</div><div><span>{job.source}</span><h3>{job.title}</h3><p><Building2 size={14}/>{job.company}</p></div><button className="job-save" onClick={() => onSave(job, saved)} aria-label={saved ? "Unsave job" : "Save job"}>{saved ? <BookmarkCheck size={19}/> : <Bookmark size={19}/>}</button></div><div className="job-meta"><span><MapPin size={14}/>{job.location || "Location unavailable"}</span><span><BriefcaseBusiness size={14}/>{job.workplace_type}</span><span><CalendarDays size={14}/>{age(job.posted_at)}</span></div><div className="job-tags">{job.skills?.slice(0, 5).map(skill => <span key={skill}>{skill}</span>)}</div><div className="job-insight"><strong><Sparkles size={14}/> Why this may fit</strong><p>{job.fit_reasons?.[0] || "Relevant to your current search criteria."}</p>{!!job.skill_gaps?.length && <small>Potential gap: {job.skill_gaps.slice(0, 3).join(", ")}</small>}</div><button className="button secondary job-view" onClick={() => onOpen(job)}>View job</button></article>;
}

function JobDetails({ job, saved, onClose, onSave }) {
  if (!job) return null;
  return <div className="job-detail-backdrop" onMouseDown={onClose}><aside className="job-detail" onMouseDown={e => e.stopPropagation()}><button className="icon-button job-detail-close" onClick={onClose}><X size={18}/></button><span className="section-eyebrow">{job.source} · Original source retained</span><h2>{job.title}</h2><h3>{job.company}</h3><div className="job-meta"><span><MapPin size={14}/>{job.location || "Unavailable"}</span><span>{job.workplace_type}</span><span>{job.employment_type || "Type unavailable"}</span></div><section><h4>CareerPilot insight</h4>{job.fit_reasons?.map(x => <p className="fit" key={x}>✓ {x}</p>)}{!!job.skill_gaps?.length && <p className="gap">Potential gaps: {job.skill_gaps.join(", ")}</p>}</section><section><h4>Description</h4><p>{clean(job.description) || "Description unavailable from this source."}</p></section><div className="job-detail-actions"><button className="button secondary" onClick={() => onSave(job, saved)}>{saved ? "Unsave job" : "Save job"}</button><a className="button primary" href={job.apply_url} target="_blank" rel="noreferrer">Open original posting <ExternalLink size={15}/></a></div><button className="button secondary" disabled>Tailor resume · Coming next</button></aside></div>;
}

export default function JobsPage() {
  const [query, setQuery] = useState(""); const [location, setLocation] = useState(""); const [workplace, setWorkplace] = useState(""); const [level, setLevel] = useState(""); const [datePosted, setDatePosted] = useState(""); const [employment, setEmployment] = useState(""); const [jobs, setJobs] = useState([]); const [saved, setSaved] = useState([]); const [profile, setProfile] = useState(null); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([careerApi.getProfile(), careerApi.listSavedJobs()]).then(([p,s]) => {setProfile(p);setSaved(s)}).catch(setError); }, []);
  const suggestions = useMemo(() => [...new Set([...(profile?.target_roles || []), profile?.professional_title, ...(profile?.skills || []).slice(0, 1).map(s => `${s.name} Developer`)].filter(Boolean))].slice(0, 4), [profile]);
  const savedFor = job => saved.find(x => x.source === job.source && x.external_job_id === job.external_id);
  const search = async e => { e?.preventDefault(); setLoading(true); setError(null); setMessage(""); try { const criteria = { query: query || suggestions[0], location: location || null, workplace_type: workplace || null, experience_level: level || null, date_posted: datePosted || null, employment_type: employment || null, limit: 24 }; const response = await careerApi.searchJobs({ criteria }); setJobs(response.jobs); setMessage(response.message || `${response.result_count} opportunities found for your profile.`); } catch (err) { setError(err); } finally { setLoading(false); }};
  const toggleSave = async (job, current) => { try { if (current) { await careerApi.unsaveJob(current.id); setSaved(x => x.filter(y => y.id !== current.id)); } else { const item = await careerApi.saveJob(job); setSaved(x => [item, ...x]); } } catch (err) { setError(err); }};
  return <main className="page jobs-page"><section className="jobs-hero"><span className="section-eyebrow">Profile-aware opportunity search</span><h1>Find your next opportunity</h1><p>CareerPilot compares real listings with the verified skills and direction in your Career Profile.</p><form onSubmit={search} className="job-search-bar"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Backend Developer or دورلي على شغل backend remote"/></label><label><MapPin size={18}/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Amman / Remote"/></label><button className="button primary" disabled={loading || (!query && !suggestions[0])}>{loading ? "Searching…" : "Search jobs"}</button></form><div className="job-filters"><select value={workplace} onChange={e=>setWorkplace(e.target.value)}><option value="">Any workplace</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="on-site">On-site</option></select><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">Any experience</option><option value="internship">Internship</option><option value="junior">Junior</option><option value="senior">Senior</option></select><select value={datePosted} onChange={e=>setDatePosted(e.target.value)}><option value="">Any date</option><option value="24h">Past 24 hours</option><option value="7d">Past week</option><option value="30d">Past month</option></select><select value={employment} onChange={e=>setEmployment(e.target.value)}><option value="">Any employment</option><option value="full-time">Full-time</option><option value="part-time">Part-time</option><option value="contract">Contract</option></select></div></section>{!jobs.length && !loading && <section className="job-suggestions"><Sparkles size={20}/><div><h2>Search with your saved Profile</h2><p>Suggested from your real career direction—not generated placeholder jobs.</p><div>{suggestions.map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div></div></section>}{message && <p className="jobs-message">{message}</p>}<AsyncState loading={loading} error={error ? { message: apiErrorMessage(error) } : null}>{!!jobs.length && <section className="job-results"><header><div><span className="section-eyebrow">Live opportunities</span><h2>{jobs.length} relevant jobs</h2></div><span>{saved.length} saved</span></header><div className="job-grid">{jobs.map(job=><JobCard key={`${job.source}:${job.external_id}`} job={job} saved={savedFor(job)} onOpen={setSelected} onSave={toggleSave}/>)}</div></section>}</AsyncState><JobDetails job={selected} saved={selected && savedFor(selected)} onClose={()=>setSelected(null)} onSave={toggleSave}/></main>;
}
