import { BriefcaseBusiness, Check, ExternalLink, FolderKanban, GraduationCap, MapPin, Pencil, Plus, Save, Trash2, UserRound, Wrench, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, NavLink, useParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import AsyncState from "../components/common/AsyncState";
import { DegreeCombobox, FieldOfStudyCombobox, GradeSystemSelector, UniversityCombobox } from "../components/selectors/EducationSelectors";
import { useCareerData, useChildMutation, useProfileMutation } from "../hooks/useCareerData";
import { calculateProfileCompletion, profileCompletionConfig } from "../services/profileCompletion";

const sections=[['Overview','',UserRound],['Education','education',GraduationCap],['Experience','experience',BriefcaseBusiness],['Projects','projects',FolderKanban],['Skills','skills',Wrench]];
const configs={experience:{title:"Experience",singular:"experience",list:"experiences",api:"experiences",icon:BriefcaseBusiness,fields:[["company","Company",true],["job_title","Role",true],["employment_type","Employment type"],["location","Location"],["start_date","Start date",false,"date"],["end_date","End date",false,"date"],["description","Role scope and impact",false,"textarea"]]},projects:{title:"Projects",singular:"project",list:"projects",api:"projects",icon:FolderKanban,fields:[["name","Project title",true],["role","Your role"],["project_url","Project link",false,"url"],["repository_url","Repository",false,"url"],["start_date","Start date",false,"date"],["end_date","End date",false,"date"],["description","What you built and why it mattered",true,"textarea"]]},skills:{title:"Skills",singular:"skill",list:"skills",api:"skills",icon:Wrench,fields:[["name","Skill",true],["category","Skill family"],["proficiency_level","Proficiency"],["years_of_experience","Years used",false,"number"]]}};

function Ring({score}){return <div className="profile-ring" style={{'--score':score}}><div><strong>{score}%</strong><span>Profile strength</span></div></div>}
function WorkspaceNav(){return <nav className="profile-local-nav">{sections.map(([label,path,Icon])=><NavLink end={!path} key={label} to={`/app/profile${path?`/${path}`:""}`}><Icon size={16}/>{label}</NavLink>)}</nav>}

function ProfileForm({profile}){const mutation=useProfileMutation();const {register,handleSubmit,reset,formState:{isDirty}}=useForm({defaultValues:{years_of_experience:0}});useEffect(()=>{if(profile)reset(profile)},[profile,reset]);return <form className="blueprint-editor" onSubmit={handleSubmit(payload=>mutation.mutate({mode:profile?"update":"create",payload:Object.fromEntries(Object.entries(payload).map(([k,v])=>[k,v===""?null:v]))}))}><header><div><span className="section-eyebrow">Career basics</span><h2>Your professional identity</h2></div><button className="button primary" disabled={mutation.isPending||(!isDirty&&profile)}><Save size={15}/> Save</button></header><div className="form-grid"><label className="span-2"><span>Professional title</span><input {...register("professional_title")} placeholder="The role that best describes you"/></label><label><span>City</span><input {...register("city")}/></label><label><span>Country</span><input {...register("country")}/></label><label className="span-2"><span>Professional summary</span><textarea rows="5" {...register("professional_summary")} placeholder="Your strengths, scope, and the value you create"/></label></div></form>}

function Overview({profile,user}){const completion=calculateProfileCompletion(profile);const stages=[['Personal profile','personal',profile?.professional_title?`${profile.professional_title} · ${profile.city||'Location open'}`:'Define your professional identity','/app/profile'],['Career direction','goals',profile?.target_roles?.length?`${profile.target_roles.length} target roles selected`:'Add goals and preferences','/app/profile'],['Education','education',`${profile?.education?.length||0} entries`,'/app/profile/education'],['Experience','experience',`${profile?.experiences?.length||0} roles`,'/app/profile/experience'],['Projects','projects',`${profile?.projects?.length||0} portfolio projects`,'/app/profile/projects'],['Skills','skills',`${profile?.skills?.length||0} skills`,'/app/profile/skills']];return <><section className="profile-blueprint-hero"><div><span className="section-eyebrow">Career Profile Blueprint</span><h1>{user?.first_name}'s professional foundation</h1><p>A connected view of the evidence CareerPilot can use across your future career tools.</p><Link className="button primary" to={completion.nextAction.to}>{completion.nextAction.label}</Link></div><Ring score={completion.score}/></section><div className="blueprint-layout"><section className="blueprint-journey">{stages.map(([label,key,summary,to],i)=>{const done=completion.categories[key];return <Link to={to} key={label} className={done?"complete":""}><span>{done?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div><small>{profileCompletionConfig[key]||10}% of profile</small><h3>{label}</h3><p>{summary}</p></div><strong>{done?'Complete':'Needs attention'}</strong>{i<stages.length-1&&<i/>}</Link>})}</section><ProfileForm profile={profile}/></div></>}

function EducationDrawer({item,onClose}){const mutation=useChildMutation();const [form,setForm]=useState(item||{});const set=(k,v)=>setForm(x=>({...x,[k]:v}));const submit=e=>{e.preventDefault();mutation.mutate({action:item?'update':'create',resource:'education',id:item?.id,payload:Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''&&v!=null))},{onSuccess:onClose})};return <div className="modal-backdrop"><section className="modal education-drawer"><header><div><span className="section-eyebrow">Academic foundation</span><h2>{item?'Edit':'Add'} education</h2></div><button className="icon-button" onClick={onClose}><X/></button></header><form onSubmit={submit}><fieldset><legend>Institution & program</legend><UniversityCombobox value={form.institution} onChange={x=>set('institution',x)} country={form.country}/><div className="form-grid"><DegreeCombobox value={form.degree} onChange={x=>set('degree',x)}/><FieldOfStudyCombobox value={form.field_of_study} onChange={x=>set('field_of_study',x)}/></div></fieldset><fieldset><legend>Study period</legend><div className="form-grid"><label><span>Start date</span><input type="date" value={form.start_date||''} onChange={e=>set('start_date',e.target.value)}/></label><label><span>End date</span><input type="date" disabled={form.is_current} value={form.end_date||''} onChange={e=>set('end_date',e.target.value)}/></label></div><label className="check-control"><input type="checkbox" checked={Boolean(form.is_current)} onChange={e=>set('is_current',e.target.checked)}/> Currently studying here</label></fieldset><fieldset><legend>Academic result</legend><GradeSystemSelector system={form.grade_system} setSystem={x=>set('grade_system',x)} grade={form.grade} setGrade={x=>set('grade',x)}/></fieldset><footer><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Save education</button></footer></form></section></div>}

function GenericDrawer({config,item,onClose}){const mutation=useChildMutation();const {register,handleSubmit}=useForm({defaultValues:item||{}});return <div className="modal-backdrop"><section className="modal"><header><h2>{item?'Edit':'Add'} {config.singular}</h2><button className="icon-button" onClick={onClose}><X/></button></header><form onSubmit={handleSubmit(payload=>mutation.mutate({action:item?'update':'create',resource:config.api,id:item?.id,payload:Object.fromEntries(Object.entries(payload).filter(([,v])=>v!==''))},{onSuccess:onClose}))}><div className="form-grid">{config.fields.map(([name,label,required,type='text'])=><label className={type==='textarea'?'span-2':''} key={name}><span>{label}</span>{type==='textarea'?<textarea rows="5" {...register(name,{required})}/>:<input type={type} {...register(name,{required,valueAsNumber:type==='number'})}/>}</label>)}</div><footer><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary">Save {config.singular}</button></footer></form></section></div>}

function EducationPage({items}){const [edit,setEdit]=useState();const mutation=useChildMutation();return <CategoryShell title="Education" copy="The academic context behind your expertise." action={()=>setEdit(null)} contribution="15% of your profile"><div className="education-timeline">{items.map(x=><article key={x.id}><time>{x.start_date?.slice(0,4)||'—'}<i/>{x.is_current?'Present':x.end_date?.slice(0,4)||'—'}</time><span/><div><small>{x.grade_system||'Education'}</small><h3>{x.institution}</h3><p>{[x.degree,x.field_of_study].filter(Boolean).join(' · ')}</p>{x.grade&&<strong>{x.grade}</strong>}</div><Actions onEdit={()=>setEdit(x)} onDelete={()=>mutation.mutate({action:'delete',resource:'education',id:x.id})}/></article>)}</div>{edit!==undefined&&<EducationDrawer item={edit} onClose={()=>setEdit(undefined)}/>}</CategoryShell>}
function Actions({onEdit,onDelete}){return <div className="resource-actions"><button className="icon-button quiet" onClick={onEdit}><Pencil size={15}/></button><button className="icon-button quiet danger" onClick={onDelete}><Trash2 size={15}/></button></div>}
function CategoryShell({title,copy,action,contribution,children}){return <section className="category-page"><header><div><span className="section-eyebrow">Career evidence · {contribution}</span><h1>{title}</h1><p>{copy}</p></div><button className="button primary" onClick={action}><Plus size={16}/> Add {title==='Skills'?'skill':title.slice(0,-1).toLowerCase()}</button></header>{children}</section>}

function GenericPage({config,items}){const [edit,setEdit]=useState();const mutation=useChildMutation();if(config.list==='skills'){const groups=Object.groupBy?Object.groupBy(items,x=>x.category||'Core skills'):items.reduce((a,x)=>((a[x.category||'Core skills']||=[]).push(x),a),{});return <CategoryShell title="Skills" copy="Grouped capabilities that describe how you create value." action={()=>setEdit(null)} contribution="20% of your profile"><div className="skill-families">{Object.entries(groups).map(([name,skills])=><section key={name}><span>{name}</span><div>{skills.map(x=><button key={x.id} onClick={()=>setEdit(x)}>{x.name}<small>{x.proficiency_level}</small></button>)}</div></section>)}</div>{edit!==undefined&&<GenericDrawer config={config} item={edit} onClose={()=>setEdit(undefined)}/>}</CategoryShell>};return <CategoryShell title={config.title} copy={config.list==='projects'?'A portfolio of work that proves what you can deliver.':'A professional timeline of your scope, impact, and growth.'} action={()=>setEdit(null)} contribution={config.list==='projects'?'15% of your profile':'25% of your profile'}><div className={`${config.list}-showcase`}>{items.map(x=><article key={x.id}><span className="entry-mark"><config.icon size={18}/></span><div><small>{[x.start_date?.slice(0,4),x.end_date?.slice(0,4)||'Present'].filter(Boolean).join(' — ')}</small><h3>{x.company||x.name}</h3><strong>{x.job_title||x.role}</strong><p>{x.description}</p>{x.project_url&&<a href={x.project_url} target="_blank" rel="noreferrer">View project <ExternalLink size={13}/></a>}</div><Actions onEdit={()=>setEdit(x)} onDelete={()=>mutation.mutate({action:'delete',resource:config.api,id:x.id})}/></article>)}</div>{edit!==undefined&&<GenericDrawer config={config} item={edit} onClose={()=>setEdit(undefined)}/>}</CategoryShell>}

export default function ProfilePage(){const {section}=useParams();const {user,profile}=useCareerData();const p=profile.data;return <main className="page profile-workspace"><header className="workspace-heading"><div><span className="section-eyebrow">Career profile</span><h1>Build the story behind your next move.</h1><p><MapPin size={14}/>{p?.city&&p?.country?`${p.city}, ${p.country}`:'Global career workspace'}</p></div></header><WorkspaceNav/><AsyncState loading={profile.isLoading} error={profile.error?.response?.status===404?null:profile.error}>{!section?<Overview profile={p} user={user.data}/>:section==='education'?<EducationPage items={p?.education||[]}/>:<GenericPage config={configs[section]} items={p?.[configs[section]?.list]||[]}/>}</AsyncState></main>}
