import { Check, ChevronDown, LoaderCircle, Search, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";

export default function PremiumCombobox({label,value,onChange,options=[],placeholder="Search…",loading=false,error,disabled=false,allowCustom=false,getLabel=(x)=>typeof x==="string"?x:x.label,getKey=(x)=>typeof x==="string"?x:(x.value||x.id||x.label)}){
  const [open,setOpen]=useState(false);const [query,setQuery]=useState("");const [active,setActive]=useState(0);const input=useRef();
  const shown=useMemo(()=>options.filter(x=>getLabel(x).toLowerCase().includes(query.toLowerCase())).slice(0,30),[options,query,getLabel]);
  const choose=(item)=>{onChange(item);setQuery("");setOpen(false)};
  const onKey=(e)=>{if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);setActive(x=>Math.min(x+1,shown.length-1))}if(e.key==="ArrowUp"){e.preventDefault();setActive(x=>Math.max(0,x-1))}if(e.key==="Enter"&&open){e.preventDefault();if(shown[active])choose(shown[active]);else if(allowCustom&&query.trim())choose(query.trim())}if(e.key==="Escape")setOpen(false)};
  return <label className="combo-field"><span>{label}</span><div className={`premium-combo ${open?"open":""} ${disabled?"disabled":""}`}><Search size={17}/><input ref={input} disabled={disabled} value={open?query:(value?getLabel(value):"")} placeholder={placeholder} onFocus={()=>{setOpen(true);setQuery("")}} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0)}} onKeyDown={onKey} role="combobox" aria-expanded={open} aria-controls={`${label}-options`}/>{value?<button type="button" aria-label={`Clear ${label}`} onClick={()=>onChange(null)}><X size={15}/></button>:loading?<LoaderCircle className="spin" size={16}/>:<ChevronDown size={16}/>} {open&&<div className="combo-menu" id={`${label}-options`} role="listbox">{shown.map((item,index)=><button type="button" role="option" aria-selected={getKey(item)===getKey(value)} className={index===active?"active":""} key={getKey(item)} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(item)}><span>{getLabel(item)}</span>{getKey(item)===getKey(value)&&<Check size={15}/>}</button>)}{allowCustom&&query.trim()&&!shown.some(x=>getLabel(x).toLowerCase()===query.toLowerCase())&&<button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>choose(query.trim())}><span>Use “{query.trim()}”</span><small>Custom entry</small></button>}{!loading&&!shown.length&&!query.trim()&&<p>Start typing to search</p>}{!loading&&!shown.length&&query.trim()&&!allowCustom&&<p>No matching options</p>}{error&&<p>{error}</p>}</div>}</div></label>;
}
