import { Briefcase, Building2, Check, Globe2, Laptop, MapPinned, Radio } from "lucide-react";
import { careerLevels, careerRoles } from "../../data/careerTaxonomies";
import PremiumCombobox from "../selectors/PremiumCombobox";

export function CareerGoalSelector({value=[],onChange,suggestions=[]}){const add=x=>{const role=typeof x==="string"?x:x.label;if(role&&!value.includes(role))onChange([...value,role])};return <div className="goal-selector"><PremiumCombobox label="What roles are you aiming for?" value={null} onChange={add} options={careerRoles} allowCustom placeholder="Search or add a role"/><span className="mini-label">Suggested for you</span><div className="goal-suggestions">{suggestions.filter(x=>!value.includes(x)).slice(0,6).map(x=><button type="button" key={x} onClick={()=>add(x)}><Briefcase size={15}/>{x}<b>+</b></button>)}</div>{value.length>0&&<><span className="mini-label">Target roles</span><div className="selected-goals">{value.map(x=><span key={x}>{x}<button type="button" aria-label={`Remove ${x}`} onClick={()=>onChange(value.filter(v=>v!==x))}>×</button></span>)}</div></>}</div>}

const modes=[["Remote","Work from anywhere",Laptop],["Hybrid","Office and remote",Building2],["On-site","Workplace based",MapPinned],["Flexible","Open to arrangements",Radio]];
export function WorkModeSelector({value=[],onChange}){const toggle=x=>onChange(value.includes(x)?value.filter(v=>v!==x):[...value,x]);return <div className="work-modes">{modes.map(([name,copy,Icon])=><button type="button" className={value.includes(name)?"selected":""} key={name} onClick={()=>toggle(name)} aria-pressed={value.includes(name)}><span><Icon size={20}/></span><strong>{name}</strong><small>{copy}</small>{value.includes(name)&&<Check className="mode-check" size={14}/>}</button>)}</div>}

export function CareerLevelSelector({value,onChange}){return <div className="level-selector">{careerLevels.map(([name,copy,years])=><button type="button" key={name} className={value===name?"selected":""} onClick={()=>onChange({name,years})}><span>{value===name?<Check size={14}/>:<Globe2 size={14}/>}</span><div><strong>{name}</strong><small>{copy}</small></div><i/></button>)}</div>}
